application: liftmo-1056
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /dev/lifts
  script: /dev/lifts.html

- url: /api/.*
  script: api/index.php

- url: /api
  script: apihelp.html

- url: /.*
  script: home.html

