application: liftmo-1056
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /test.*
  script: test/test.php

- url: /api.*
  script: index.php

- url: /.*
  script: home.html

