application: liftmo-1056
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: index.php

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /html
  static_dir: html

- url: /api.*
  script: api.php

#- url: /(.+\.php)
#  script: api.php

- url: /.*
  script: index.html
