application: liftmo-1056
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

#- url: /api
#  static_dir: api

#- url: /api.*
#  script: api/index.php

- url: /api/.*
  script: api/index.php

- url: /.*
  script: home.html

